/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Version = string;
export type I18NKey = string;
export type Tag = I18NKey[];
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9_\.\-]*$".
 */
export type ResourceRoot = string;
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "[\s\S]*".
 */
export type Config =
  | string[]
  | string
  | boolean
  | number
  | {
      [k: string]: unknown;
    };
/**
 * Represents the definition of each route
 */
export type Route = RouteWithoutName & {
  /**
   * Represents the name of the route
   */
  name: string;
  [k: string]: unknown;
};
/**
 * Represents the card default grid size in columns and rows
 */
export type DefaultSpanDef =
  | {
      /**
       * Represents the number of the number of grid columns
       */
      cols: number;
      /**
       * Represents the number of the number of grid rows
       */
      rows: number;
    }
  | "auto";

export interface SAPJSONSchemaForWebApplicationManifestFile {
  /**
   * Represents Application Descriptor format version. It is managed by schema owner
   */
  _version: "1.1.0" | "1.2.0" | "1.3.0" | "1.4.0";
  /**
   * Represents the URL that the developer would prefer the user agent load when the user launches the web application
   */
  start_url?: string;
  "sap.app": JSONSchemaForSAPAPPNamespace;
  "sap.ui": JSONSchemaForSAPUINamespace;
  "sap.ui5"?: JSONSchemaForSAPUI5Namespace;
  "sap.platform.abap"?: JSONSchemaForSAPPLATFORMABAPNamespace;
  "sap.platform.hcp"?: JSONSchemaForSAPPLATFORMHCPNamespace;
  "sap.fiori"?: JSONSchemaForSAPFIORINamespace;
  "sap.ui.generic.app"?: JSONSchemaForSAPUIGENERICAPPNamespace;
  "sap.flp"?: JSONSchemaForSAPFLPNamespace;
  "sap.ovp"?: JSONSchemaForSAPOVPNamespace;
  "sap.wda"?: JSONSchemaForSAPWDANamespace;
  "sap.apf"?: JSONSchemaForSAPAPFNamespace;
  "sap.cloud.portal"?: JSONSchemaForSAPCLOUDPORTALNamespace;
  "sap.gui"?: JSONSchemaForSAPGUINamespace;
  "sap.ui.smartbusiness.app"?: JSONSchemaForSAPUISMARTBUSINESSAPPNamespace;
  "sap.mobile"?: JSONSchemaForSAPMOBILENamespace;
}
/**
 * Represents general application attributes
 */
export interface JSONSchemaForSAPAPPNamespace {
  /**
   * Application attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0" | "1.3.0" | "1.4.0";
  /**
   * Represents the template from which the app was generated
   */
  sourceTemplate?: {
    /**
     * Represents id of the template from which the app was generated
     */
    id: string;
    /**
     * Represents the version of the template from which the app was generated
     */
    version: string;
    [k: string]: unknown;
  };
  /**
   * Represents mandatory unique app identifier which must correspond to component 'id/namespace'
   */
  id: string;
  /**
   * Represents type of an application and can be application or component or library
   */
  type: "application" | "component" | "library";
  /**
   * Represents path inside the app to the properties file containing text symbols for the Descriptor
   */
  i18n?: string;
  /**
   * Represents mandatory version of the app
   */
  applicationVersion: {
    version: Version;
    [k: string]: unknown;
  };
  /**
   * Represents array of relative paths to the nested manifest.json's (mandatory if it contains nested 'manifest.json')
   */
  embeds?: string[];
  /**
   * Represents relative path back to the manifest.json of an embedding component or library (mandatory for nested 'manifest.json')
   */
  embeddedBy?: string;
  /**
   * Represents language-dependent mandatory title
   */
  title: string;
  /**
   * Represents language-dependent additional information to the title
   */
  subTitle?: string;
  /**
   * Represents language-dependent description
   */
  description?: string;
  /**
   * Represents array of keywords
   */
  tags?: {
    keywords: Tag;
    [k: string]: unknown;
  };
  /**
   * Represents application component hierarchy
   */
  ach?: string;
  /**
   * Represents used data sources with a unique key/alias
   */
  dataSources?: {
    [k: string]: DataSource;
  };
  /**
   * Represents array of directly used CDS views, which only to be added if directly used via INA protocol and not if used via OData service
   */
  cdsViews?: string[];
  /**
   * Represents reference to a file (naming convention is resources.json) which contains list with all resources which the app needs
   */
  resources?: "resources.json";
  /**
   * Represents a system alias
   */
  destination?: {
    /**
     * Represents an alias for the system
     */
    name: string;
  };
  /**
   * Represents a collection of directly used open source libs (not when used via UI5 capsulation)
   */
  openSourceComponents?: OpenSource[];
  /**
   * Represents indicator whether the app is running offline. Possible values are true or false (default)
   */
  offline?: boolean;
  /**
   * Represents cross navigation for inbound and outbound targets
   */
  crossNavigation?: {
    /**
     * Represents scopes of a site
     */
    scopes?: {
      /**
       * Represents unique id of the site
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[\w\.\-]+$".
       */
      [k: string]: {
        value: string;
        [k: string]: unknown;
      };
    };
    inbounds: Inbound;
    outbounds?: Outbound;
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[\w\.\-]*$".
 */
export interface DataSource {
  /**
   * Represents uri of the data source
   */
  uri: string;
  /**
   * Represents type of the data source. The supported types are OData, ODataAnnotation, INA, XML, JSON
   */
  type?: "OData" | "ODataAnnotation" | "INA" | "XML" | "JSON";
  settings?: Setting;
}
/**
 * Represents data source type specific attributes (key, value pairs)
 */
export interface Setting {
  /**
   * Represents version of OData: 2.0 is default
   */
  odataVersion?: "2.0" | "4.0";
  /**
   * Represents path to local meta data document or annotation uri
   */
  localUri?: string;
  /**
   * Represents  array of annotation which references an existing data source of type ODataAnnotation
   */
  annotations?: string[];
  /**
   * Indicates that the client is unwilling to accept a response whose age is greater than the number of seconds specified in this field
   */
  maxAge?: number;
}
export interface OpenSource {
  /**
   * Represents a name of the open source as appears on the web
   */
  name: string;
  /**
   * Represents a version of the open source (if part of app, version must be specified, if part of UI5 dist layer, version is empty)
   */
  version?: string;
  /**
   * Indicates, whether it is part of the app or not
   */
  packagedWithMySelf?: boolean;
}
/**
 * Represents cross navigation for inbound target
 */
export interface Inbound {
  /**
   * This interface was referenced by `Inbound`'s JSON-Schema definition
   * via the `patternProperty` "^[\w\.\-]+$".
   */
  [k: string]: {
    /**
     * Represents semantic object
     */
    semanticObject: string;
    /**
     * Represents action an the semantic object
     */
    action: string;
    /**
     * Represents icon
     */
    icon?: string;
    /**
     * Represents language-dependent - different languages via server API or on client
     */
    title?: I18NKey;
    /**
     * Represents language-dependent additional information to the title and can overwrite subTitle from sap.app definition
     */
    subTitle?: I18NKey;
    /**
     * Represents language-dependent  additional information to the title
     */
    info?: string;
    /**
     * Represents data source
     */
    indicatorDataSource?: {
      dataSource: string;
      path: string;
      /**
       * Represents refresh interval
       */
      refresh?: number;
      [k: string]: unknown;
    };
    deviceTypes?: DeviceType;
    signature?: SignatureDef;
  };
}
/**
 * Represents device types for which application is developed
 */
export interface DeviceType {
  /**
   * Represents indicator whether desktop device is supported, default true
   */
  desktop?: boolean;
  /**
   * Represents indicator whether tablet device is supported, default true
   */
  tablet?: boolean;
  /**
   * Represents indicator whether phone device is supported, default true
   */
  phone?: boolean;
}
/**
 * Represents signature for inbound targets
 */
export interface SignatureDef {
  parameters: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[\w\.\-]+$".
     */
    [k: string]: {
      /**
       *  Represents a default Value
       */
      defaultValue?: {
        /**
         * Represents a depending on format either a verbatim default value or a reference
         */
        value: string;
        /**
         * Indicates how 'value' is to be interpreted: ('plain': the 'value' is taken as a literal string value| 'reference': the 'value' is a reference to e.g. a UserDefault parameter (e.g. 'UserDefault.CostCenter'), the resolved parameter value is used)
         */
        format?: "plain" | "reference";
      };
      /**
       * Represents a filter , only if input parameter matches filter
       */
      filter?: {
        /**
         * Represents a depending on format either a verbatim filter value, a regular expression or a reference
         */
        value: string;
        /**
         * Indicates how 'value' is to be interpreted: ('plain': the actual value must match the 'value' property directly| 'regexp': the 'value' represents a regexp which must be present in the actual value| 'reference' : the 'value' represents a reference to e.g. a UserDefault parameter (e.g. 'UserDefault.CostCenter'), the resolved parameter value is then directly compared with the actual value)
         */
        format?: "plain" | "regexp" | "reference";
      };
      required?: boolean;
      /**
       * Represents the parameter name in legacy ABAP application, e.g. 'RF05L-BUKRS' for parameter 'CompanyCode'
       */
      renameTo?: string;
    };
  };
  /**
   * Indicates how additional parameters to the declared signature are treated: ('ignored': parameters are not passed on to application | 'allowed': parameters are passed on to application | 'notallowed': additional parameters are not allowed)
   */
  additionalParameters: "ignored" | "allowed" | "notallowed";
}
/**
 * Represents cross navigation for outbound target
 */
export interface Outbound {
  /**
   * This interface was referenced by `Outbound`'s JSON-Schema definition
   * via the `patternProperty` "^[\w\.\-]+$".
   */
  [k: string]: {
    /**
     * Represents semantic object
     */
    semanticObject: string;
    /**
     * Represents action an the semantic object
     */
    action: string;
    /**
     * Represents parameters for outbound targets
     */
    parameters?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[\w\.\-]+$".
       */
      [k: string]: {
        [k: string]: unknown;
      };
    };
  };
}
/**
 * Represents general ui attributes
 */
export interface JSONSchemaForSAPUINamespace {
  /**
   * Represents UI attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0" | "1.3.0" | "1.4.0";
  /**
   * Represents UI technology. The possible values are UI5 (default), WDA, NWBC and URL
   */
  technology: "UI5" | "WDA" | "NWBC" | "GUI" | "URL";
  /**
   * Represents icons which used in application
   */
  icons?: {
    /**
     * Represents icon of the app
     */
    icon?: string;
    /**
     * Represents ICO file to be used inside the browser and for desktop shortcuts
     */
    favIcon?: string;
    /**
     * Represents 57x57 pixel version for non-retina iPhones
     */
    phone?: string;
    /**
     * Represents 114x114 pixel version for non-retina iPhones
     */
    "phone@2"?: string;
    /**
     * Represents 72x72 pixel version for non-retina iPads
     */
    tablet?: string;
    /**
     * Represents 144x144 pixel version for non-retina iPads
     */
    "tablet@2"?: string;
  };
  /**
   * Represents device types on which application is running. Supported device types are desktop, tablet and phone
   */
  deviceTypes: DeviceType1 & {
    [k: string]: unknown;
  };
  /**
   * Represents array of supported SAP themes such as sap_hcb, sap_bluecrystal
   */
  supportedThemes?: string[];
  /**
   * Indicates whether app should run in full screen mode: possible values: true or false
   */
  fullWidth?: boolean;
  [k: string]: unknown;
}
/**
 * Represents device types on which the app is running
 */
export interface DeviceType1 {
  /**
   * Represents indicator whether desktop device is supported, default true
   */
  desktop?: boolean;
  /**
   * Represents indicator whether tablet device is supported, default true
   */
  tablet?: boolean;
  /**
   * Represents indicator whether phone device is supported, default true
   */
  phone?: boolean;
}
/**
 * Represents sapui5 attributes
 */
export interface JSONSchemaForSAPUI5Namespace {
  /**
   *  Represents SAPUI5 attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0" | "1.3.0";
  resources?: Resource;
  /**
   * Represents external dependences such as libraries or components, that will be loaded by UI5 Core in the initialization phase of your Component and can be used after it
   */
  dependencies: {
    /**
     * Represents the minimum version of SAP UI5 that your component requires
     */
    minUI5Version: string;
    /**
     * Represents ...
     */
    incompatibleLimitation?: boolean;
    /**
     * Represents the id (namespace) of the libraries that should be loaded by UI5 Core to be used in your component
     */
    libs?: {
      [k: string]: Lib;
    };
    /**
     * Represents the id (namespace) of the components that should be loaded by UI5 Core to be used in your component
     */
    components?: {
      [k: string]: Component;
    };
  };
  /**
   * Represents models which should be created/destroyed with the life-cycle of the component
   */
  models?: {
    [k: string]: Model;
  };
  /**
   * Represents relative path to the resource. Only relative path allowed, no '../'
   */
  resourceRoots?: {
    [k: string]: ResourceRoot;
  };
  /**
   * Represents the name of the root view
   */
  rootView?:
    | string
    | {
        /**
         * Represents the name of the view
         */
        viewName: string;
        /**
         * Represents the type of the view. Possible Values: XML, JSON, JS, HTML, Template
         */
        type?: "XML" | "JSON" | "JS" | "HTML" | "Template";
        [k: string]: unknown;
      };
  /**
   * Represents the usage of validation handling by MessageManager for this component (enable/disable)
   */
  handleValidation?: boolean;
  /**
   * Represents the static configuration for components
   */
  config?: {
    [k: string]: Config;
  };
  /**
   * Represents the configuration of routing
   */
  routing?: {
    /**
     * Represents the default properties defined for route and target
     */
    config?: {
      /**
       * Represents the router class
       */
      routerClass?: string;
      /**
       * Indicates whether the Views in routing are loaded asyncly
       */
      async?: boolean;
      /**
       * Represents information about targets to display when no route is matched
       */
      bypassed?: {
        /**
         * Represents one or multiple names of targets that are displayed when no route is matched
         */
        target: string[] | string;
      };
      [k: string]: unknown;
    } & Target;
    routes?:
      | Route[]
      | {
          [k: string]: RouteWithoutName;
        };
    /**
     * Represents the definition of targets
     */
    targets?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "[\s\S]*".
       */
      [k: string]: Target & {
        /**
         * Represents the name of a view that will be created
         */
        viewName: string;
        [k: string]: unknown;
      } & {
        /**
         * Represents the id of the created view
         */
        viewID?: string;
        [k: string]: unknown;
      };
    };
    [k: string]: unknown;
  };
  /**
   * Represents the extension of an additional component
   */
  extends?: {
    /**
     * Represents the component name
     */
    component?: string;
    /**
     * Represents minimal version of the component
     */
    minVersion?: string;
    /**
     * Represents extensions of the component
     */
    extensions?: {
      [k: string]: unknown;
    };
  };
  /**
   * Represents object with content density modes the app is supporting. Supported density modes are 'cozy' and 'compact'
   */
  contentDensities: {
    /**
     * Represents indicator whether compact mode is supported
     */
    compact: boolean;
    /**
     * Represents indicator whether cozy mode is supported
     */
    cozy: boolean;
  };
  /**
   * Represents a name of the UI5 component
   */
  componentName?: string;
  /**
   * Enables the auto prefixing of IDs of ManagedObjects (e.g. Controls) which are created in context of the Component (e.g. createContent invocation)
   */
  autoPrefixId?: boolean;
  /**
   * Represents the identifier of an application variant. The value will be calculated and should not be set manually
   */
  appVariantId?: string;
  /**
   * Represents a list of the services
   */
  services?: {
    [k: string]: Service;
  };
}
/**
 * Represents paths to JavaScript/CSS resources that your app needs (app internal), formerly called '.includes'
 */
export interface Resource {
  js?: {
    uri: string;
    [k: string]: unknown;
  }[];
  css?: {
    uri: string;
    id?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * Represents sapui5 library name
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^([a-z][a-z0-9]{0,39})(\.[a-z][a-z0-9]{0,39})*$".
 */
export interface Lib {
  /**
   * Represents minimal version of ui5 library
   */
  minVersion?: string;
  /**
   * Represents ...
   */
  lazy?: boolean;
  [k: string]: unknown;
}
/**
 * Represents sapui5 component name
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^([a-z_$][a-z0-9_$]{0,39}\.)*([a-zA-Z_$][a-zA-Z0-9_$]{0,39})$".
 */
export interface Component {
  /**
   * Represents minimal version of ui5 component
   */
  minVersion?: string;
  /**
   * Represents ...
   */
  lazy?: boolean;
  [k: string]: unknown;
}
/**
 * Represents sapui5 model name
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9_\.\-\|\@]*$".
 */
export interface Model {
  /**
   * Represents model class name
   */
  type?: string;
  /**
   * Represents string of key/alias from sap.app dataSources to reference an existing data source
   */
  dataSource?: string;
  /**
   * Represents URI for the model
   */
  uri?: string;
  /**
   * Indicates that the model will be immediately created after the manifest is loaded by Component Factory and before the Component instance is created
   */
  preload?: boolean;
  settings?: Ui5Setting;
}
export interface Ui5Setting {
  /**
   * Represents default binding mode and must be a string value from sap.ui.model.BindingMode. Possible values: Default, OneTime, OneWay, TwoWay
   */
  defaultBindingMode?: "Default" | "OneTime" | "OneWay" | "TwoWay";
  [k: string]: unknown;
}
/**
 * Represents the definition of each target
 */
export interface Target {
  /**
   * Represents the type of view that is going to be created
   */
  viewType?: "XML" | "JSON" | "JS" | "HTML" | "Template";
  /**
   * Represents a prefix that is prepended in front of the viewName
   */
  viewPath?: string;
  /**
   * Represents the id of the view that contains the control specified by the 'controlId'
   */
  targetParent?: string;
  /**
   * Represents the id of the control where you want to place the view created by the target
   */
  controlId?: string;
  /**
   * Represents the name of an aggregation of the controlId that contains the views
   */
  controlAggregation?: string;
  /**
   * Whether the aggregation of the control should be cleared before adding the view
   */
  clearControlAggregation?: boolean;
  /**
   * Represents the name of another target which will also be displayed once this target is displayed
   */
  parent?: string;
  /**
   * Represents the level of the current view which is used to define the transition direction when navigate to this view
   */
  viewLevel?: number;
  /**
   * Represents the type of transition when navigating from previous view to this view
   */
  transition?: string | ("slide" | "flip" | "fade" | "show");
  /**
   * Represents the transition parameters that are passed to the event handlers
   */
  transitionParameters?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Represents the definition of route without the option 'name'. This is used when routes are defined in an object.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "[\s\S]*".
 */
export interface RouteWithoutName {
  /**
   * Represents the url pattern that the route is matched against
   */
  pattern?: string;
  /**
   * Whether the route should be matched when another route is already matched
   */
  greedy?: boolean;
  /**
   * Represents one or multiple names of targets which are displayed when the route is matched
   */
  target?: string[] | string;
  [k: string]: unknown;
}
/**
 * Represents the definition of each service
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "[\s\S]*".
 */
export interface Service {
  /**
   * Represents the name of the service factory
   */
  factoryName: string;
  /**
   * Indicates whether the service optional or not
   */
  optional?: boolean;
  [k: string]: unknown;
}
/**
 * Represents ABAP platform specific attributes
 */
export interface JSONSchemaForSAPPLATFORMABAPNamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0";
  /**
   * Represents the uri of the app in the ABAP system
   */
  uri?: string;
  /**
   * Represents the alternative uri of the app in the ABAP system for starting the application
   */
  uriNwbc?: string;
}
/**
 * Represents HANA Cloud Platform platform specific attributes
 */
export interface JSONSchemaForSAPPLATFORMHCPNamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0" | "1.3.0";
  /**
   * Represents the uri of the app in the HANA Cloud Platform
   */
  uri?: string;
  /**
   * Represents the alternative uri of the app in the ABAP system for starting the application
   */
  uriNwbc?: string;
  /**
   * Represents the provider account of the HTML5 application
   */
  providerAccount?: string;
  /**
   * Represents the HTML5 application name
   */
  appName?: string;
  /**
   * Represents the version of the HTML5 application
   */
  appVersion?: string;
  /**
   * Indicates that HCP application is multi-version enabled
   */
  multiVersionApp?: boolean;
}
/**
 * Represents SAP Fiori  specific attributes
 */
export interface JSONSchemaForSAPFIORINamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0";
  /**
   * Represents array of registration ids, i.e. for Fiori apps fiori id(s)
   */
  registrationIds: string[];
  /**
   * Represents architecture type of an application. The supported types are transactional or analytical or factsheet or reusecomponent or fpmwebdynpro or designstudio
   */
  archeType: "transactional" | "analytical" | "factsheet" | "reusecomponent" | "fpmwebdynpro" | "designstudio";
}
/**
 * Represents GENERIC APP specific attributes
 */
export interface JSONSchemaForSAPUIGENERICAPPNamespace {
  _version?: "1.1.0" | "1.2.0";
  settings?: SettingDef;
  /**
   * Represents one ore more pages of an application. UI5 routing is created from the definitions in this section
   */
  pages?: Page[];
}
/**
 * Represents global settings for the application controller
 */
export interface SettingDef {
  [k: string]: unknown;
}
export interface Page {
  /**
   * Represents the navigation property that leads to this page. The navigation links of the previous page (the page that calls this one) are determined through this property
   */
  navigationProperty?: string;
  /**
   * Represents the entity set that defines either the aggregation or the root object of the component
   */
  entitySet: string;
  component: ComponentDef;
  navigation?: NavigationDef;
  embeddedComponents?: EmbeddedComponent;
  pages?: Page[];
}
/**
 * Represents the component and its settings that makes the page
 */
export interface ComponentDef {
  /**
   * The name of the component
   */
  name: string;
  /**
   * Switch to create a route for a list (aggregation) if true and routing for an entity if not set or false
   */
  list?: boolean;
  settings?: ComponentSettingDef;
}
/**
 * Represents the settings specific to one component
 */
export interface ComponentSettingDef {
  [k: string]: unknown;
}
/**
 * Represents the different navigation targets
 */
export interface NavigationDef {
  display?: ActionPropDef;
  create?: ActionPropDef1;
  edit?: ActionPropDef2;
}
/**
 * Represents an action triggered by the user on UI: the navigation to display an object
 */
export interface ActionPropDef {
  /**
   * Represents the path in the manifest to the target to which the navigation is bound
   */
  path: string;
  /**
   * Represents the pointer to a semantic object
   */
  target: string;
}
/**
 * Represents an action triggered by the user on UI: the navigation to create an object
 */
export interface ActionPropDef1 {
  /**
   * Represents the path in the manifest to the target to which the navigation is bound
   */
  path: string;
  /**
   * Represents the pointer to a semantic object
   */
  target: string;
}
/**
 * Represents an action triggered by the user on UI: the navigation to edit an object
 */
export interface ActionPropDef2 {
  /**
   * Represents the path in the manifest to the target to which the navigation is bound
   */
  path: string;
  /**
   * Represents the pointer to a semantic object
   */
  target: string;
}
/**
 * Represent reuse components that should be appended at the end of the template component
 */
export interface EmbeddedComponent {
  /**
   * This interface was referenced by `EmbeddedComponent`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_\.\-\:]+$".
   */
  [k: string]: {
    /**
     * Represents an unique id for the instance of the reuse component inside of the object page
     */
    id: string;
    /**
     * Represents the title for the content of the reuse component
     */
    title: string;
    /**
     * Represents an optional element binding  for the ComponentContainer that hosts the reuse component
     */
    binding?: string;
    /**
     * Represents a map to populate the API of the reuse component
     */
    settings?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  } & (
    | {
        /**
         * Represents the name of the reuse component
         */
        componentName: string;
        [k: string]: unknown;
      }
    | {
        embeddedComponents: EmbeddedComponent1;
        [k: string]: unknown;
      }
  );
}
export interface EmbeddedComponent1 {
  /**
   * This interface was referenced by `EmbeddedComponent`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_\.\-\:]+$".
   */
  [k: string]: {
    /**
     * Represents an unique id for the instance of the reuse component inside of the object page
     */
    id: string;
    /**
     * Represents the title for the content of the reuse component
     */
    title: string;
    /**
     * Represents an optional element binding  for the ComponentContainer that hosts the reuse component
     */
    binding?: string;
    /**
     * Represents a map to populate the API of the reuse component
     */
    settings?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  } & (
    | {
        /**
         * Represents the name of the reuse component
         */
        componentName: string;
        [k: string]: unknown;
      }
    | {
        embeddedComponents: EmbeddedComponent1;
        [k: string]: unknown;
      }
  );
}
/**
 * Represents FLP specific attributes
 */
export interface JSONSchemaForSAPFLPNamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0";
  /**
   * Represents size of the tile
   */
  tileSize?: "1x1" | "1x2";
  /**
   * Represents the type of FLP entry. It must be 'application' or 'tile' or 'plugin'
   */
  type: "application" | "tile" | "plugin";
  /**
   * Represents configuration parameters of the FLP entry
   */
  config: {
    /**
     * Represents the configuration key and values
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\_\.\-]*$".
     */
    [k: string]: {
      [k: string]: unknown;
    };
  };
}
/**
 * Represents OVP specific attributes
 */
export interface JSONSchemaForSAPOVPNamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0";
  /**
   * Represents the name of global filter OData model, which  contains entities definition that are relevant for global filters
   */
  globalFilterModel?: string;
  /**
   * Represents the entity to use as global filter in the smart filter bar control
   */
  globalFilterEntityType?: string;
  /**
   * Represents the layout of the card container
   */
  containerLayout?: "easyScan" | "dashboard";
  cards: {
    [k: string]: Card;
  };
  dashboardLayout?: {
    [k: string]: DashboardLayoutVariant;
  };
}
/**
 * Represents the card attributes
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9_\.\-]+$".
 */
export interface Card {
  /**
   * Represents the position of the card in the sequence
   */
  sequencePos?: number;
  /**
   * Represents the model for the card
   */
  model?: string;
  /**
   * Represents the card component path to use for this card
   */
  template: string;
  settings?: CardSetting;
  /**
   * Represents the card with view switch control
   *
   * @minItems 1
   */
  tabs?: [TabSetting, ...TabSetting[]];
}
/**
 * Represents the card specific properties - properties that are passed to the card
 */
export interface CardSetting {
  /**
   * Represents the category of the card- used in the card header
   */
  category?: string;
  /**
   * Represents language-dependent title of the card - used in the card header
   */
  title?: string;
  /**
   * Represents language-dependent subtitle of the card - used in the card header
   */
  subTitle?: string;
  /**
   * Represents the entity set that will be displayed in this card
   */
  entitySet?: string;
  /**
   * Represents the static content that will be displayed in this card
   */
  staticContent?: {
    [k: string]: unknown;
  }[];
  /**
   * Represents the flavor of the list to use in this card. The flavor can be bar chart, carousel or standard
   */
  listFlavor?: "standard" | "bar" | "carousel";
  /**
   * Represents the type of list to use for this card. The list can be extended to display more information or condensed to take up less space on the card
   */
  listType?: "extended" | "condensed";
  /**
   * Represents the sort key for the entity set
   */
  sortBy?: string;
  /**
   * Represents the sort order for the entity set
   */
  sortOrder?: "ascending" | "descending";
  /**
   * Represents the annotation path
   */
  annotationPath?: string;
  /**
   * Represents the selection annotation path
   */
  selectionAnnotationPath?: string;
  /**
   * Represents the chart annotation path
   */
  chartAnnotationPath?: string;
  /**
   * Represents the presentation annotation path
   */
  presentationAnnotationPath?: string;
  /**
   * Represents the data point annotation path
   */
  dataPointAnnotationPath?: string;
  /**
   * Represents the identification annotation path
   */
  identificationAnnotationPath?: string;
  /**
   * Represents the flag to indicate priority of number formatting over sap text
   */
  ignoreSapText?: boolean;
  defaultSpan?: DefaultSpanDef;
  /**
   * Represents the cards for which authorization is required
   */
  requireAppAuthorization?: string;
  [k: string]: unknown;
}
/**
 * Represents the tab specific properties - properties that are passed to a particular tab in a card
 */
export interface TabSetting {
  /**
   * Represents the annotation path
   */
  annotationPath?: string;
  /**
   * Represents the selection annotation path
   */
  selectionAnnotationPath?: string;
  /**
   * Represents the chart annotation path
   */
  chartAnnotationPath?: string;
  /**
   * Represents the presentation annotation path
   */
  presentationAnnotationPath?: string;
  /**
   * Represents the data point annotation path
   */
  dataPointAnnotationPath?: string;
  /**
   * Represents the identification annotation path
   */
  identificationAnnotationPath?: string;
  /**
   * Represents the drop down value to be shown
   */
  value?: string;
  [k: string]: unknown;
}
/**
 * Represents the dashboard layout variant
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^cols_[0-9]+$".
 */
export interface DashboardLayoutVariant {
  [k: string]: DashboardLayoutVariantCardProperties;
}
/**
 * Represents the card properties is a layout variant
 *
 * This interface was referenced by `DashboardLayoutVariant`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9_\.\-]+$".
 */
export interface DashboardLayoutVariantCardProperties {
  /**
   * Represents the grid column
   */
  col: number;
  /**
   * Represents the grid row
   */
  row: number;
  /**
   * Represents the column span
   */
  colSpan: number;
  /**
   * Represents the row span
   */
  rowSpan: number;
  /**
   * Represents the visibility of the card
   */
  visible?: boolean;
}
/**
 * Represents WDA specific attributes
 */
export interface JSONSchemaForSAPWDANamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0";
  /**
   * Represents ID of an application
   */
  applicationId: string;
  /**
   * Represents ID of an application configuration
   */
  configId?: string;
  /**
   * Represents SAP Screen Personas Flavor ID
   */
  flavorId?: string;
}
/**
 * Represents APF specific attributes
 */
export interface JSONSchemaForSAPAPFNamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0";
  /**
   * Represents a switch to activate filter reduction so that filters in OData requests can be represented as ABAP select options
   */
  activateFilterReduction?: boolean;
  /**
   * Represents a switch to activate LREP as the persistence for configurations and texts
   */
  activateLrep?: boolean;
}
/**
 * Represents Cloud Portal specific attributes
 */
export interface JSONSchemaForSAPCLOUDPORTALNamespace {
  [k: string]: unknown;
}
/**
 * Represents GUI specific attributes
 */
export interface JSONSchemaForSAPGUINamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0" | "1.2.0";
  /**
   * Represents transaction of an application
   */
  transaction: string;
  /**
   * Represents SAP Screen Personas Flavor ID
   */
  flavorId?: string;
}
/**
 * Represents specific attributes for Smart Business
 */
export interface JSONSchemaForSAPUISMARTBUSINESSAPPNamespace {
  [k: string]: unknown;
}
/**
 * Represents mobile specific attributes
 */
export interface JSONSchemaForSAPMOBILENamespace {
  /**
   * Represents attributes format version. It is managed by namespace owner
   */
  _version?: "1.1.0";
  /**
   * Represents mobile specific attributes
   */
  definingRequests: {
    [k: string]: DefiningRequest;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9_\.\-]*".
 */
export interface DefiningRequest {
  /**
   * Represents reference to dataSource under sap.app
   */
  dataSource: string;
  /**
   * Represents path to the title collection
   */
  path: string;
  /**
   * Represents indicator whether streams should be retrieved
   */
  retrieveStreams?: boolean;
}
